spring.application.name=biteplate-srms-assignment-ready
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/biteplate_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Saidkxon_2003}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.seed.default-password=${APP_SEED_PASSWORD:1234}

spring.web.resources.static-locations=classpath:/static/

spring.jpa.packages-to-scan=com.biteplate.domain
